# Generated by Django 5.0.6 on 2024-06-08 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netfiex_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorymodel',
            name='slug',
            field=models.SlugField(max_length=250, unique=True),
        ),
    ]
