# Generated by Django 5.0.6 on 2024-06-08 10:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netfiex_app', '0002_alter_categorymodel_slug'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='watcchListModel',
            new_name='watchListModel',
        ),
        migrations.RemoveField(
            model_name='reviewmodel',
            name='rating',
        ),
        migrations.AddField(
            model_name='reviewmodel',
            name='like',
            field=models.BooleanField(default=True),
        ),
    ]
