# Generated by Django 5.0.6 on 2024-06-12 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netfiex_app', '0003_rename_watcchlistmodel_watchlistmodel_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contentmodel',
            name='category',
        ),
        migrations.AddField(
            model_name='contentmodel',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='netfiex_app.categorymodel'),
        ),
    ]
