# Generated by Django 5.0.6 on 2024-06-12 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netfiex_app', '0004_remove_contentmodel_category_contentmodel_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentmodel',
            name='dueration',
            field=models.DateTimeField(),
        ),
    ]
