# Generated by Django 5.0.6 on 2024-06-12 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netfiex_app', '0005_alter_contentmodel_dueration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contentmodel',
            name='dueration',
        ),
        migrations.AlterField(
            model_name='contentmodel',
            name='relase_date',
            field=models.DateTimeField(),
        ),
    ]
