# Generated by Django 5.0.6 on 2024-06-15 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netfiex_app', '0006_remove_contentmodel_dueration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewmodel',
            name='like',
            field=models.BooleanField(default=False),
        ),
    ]
