# Generated by Django 5.0.6 on 2024-06-20 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netfiex_app', '0007_alter_reviewmodel_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentmodel',
            name='videofile',
            field=models.FileField(null=True, upload_to='netfiex_app/videos'),
        ),
    ]
