# Generated by Django 4.2.6 on 2024-07-18 15:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('netfiex_app', '0008_alter_contentmodel_videofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contentmodel',
            name='director',
        ),
        migrations.AddField(
            model_name='contentmodel',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='author', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
