# Generated by Django 4.2.6 on 2024-07-18 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netfiex_app', '0009_remove_contentmodel_director_contentmodel_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentmodel',
            name='thumbell',
            field=models.ImageField(null=True, upload_to='netfiex_app/image'),
        ),
    ]
