# Generated by Django 4.2.6 on 2024-07-25 15:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('netfiex_app', '0010_contentmodel_thumbell'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='watchListModel',
            new_name='LikeModel',
        ),
        migrations.RemoveField(
            model_name='reviewmodel',
            name='like',
        ),
        migrations.AddField(
            model_name='contentmodel',
            name='likes_count',
            field=models.IntegerField(default=0),
        ),
    ]
