# Generated by Django 4.2.6 on 2024-07-25 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netfiex_app', '0011_rename_watchlistmodel_likemodel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentmodel',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='contentmodel',
            name='relase_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
