# Generated by Django 4.2.6 on 2024-07-29 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('netfiex_app', '0012_contentmodel_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contentmodel',
            old_name='likes_count',
            new_name='view_count',
        ),
        migrations.DeleteModel(
            name='LikeModel',
        ),
    ]
