# Generated by Django 4.2.6 on 2024-07-29 11:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('netfiex_app', '0013_rename_likes_count_contentmodel_view_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contentmodel',
            name='view_count',
        ),
        migrations.AddField(
            model_name='contentmodel',
            name='view_count',
            field=models.ManyToManyField(related_name='content_view', to=settings.AUTH_USER_MODEL),
        ),
    ]
