# Generated by Django 4.2.6 on 2024-08-01 13:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('netfiex_app', '0015_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentmodel',
            name='like',
            field=models.ManyToManyField(related_name='content_like', to=settings.AUTH_USER_MODEL),
        ),
    ]
