# Generated by Django 4.2.6 on 2024-08-01 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('netfiex_app', '0017_remove_contentmodel_like_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='content',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='like', to='netfiex_app.contentmodel'),
        ),
    ]
